name:                freewill
version:             0.1.0.0
homepage:            https://github.com/githubuser/alksjdhflaksjhdf#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - servant-server
  - servant-swagger
  - servant-foreign
  - servant-js
  - servant-auth
  - wai
  - wai-cors
  - wai-util
  - wai-extra
  - warp
  - bytestring
  - http-types
  - mtl
  - ghc-prim
  - swagger2
  - text
  - lens
  - safe
  - transformers
  - stm
  - postgresql-simple
  - servant-options
  - http-api-data
  - servant-auth-server
  - servant-auth-swagger
  - cookie
  - groom
  - directory
  - jose
  - random
  - uuid
  - generic-lens

library:
  source-dirs: src
  exposed-modules: ['Network.Wai.Middleware.Debugging', 'Context', 'API','Lib','Enhancements','DB.Class','DB.MemDB','DB.PostgresDB']

executables:
  freewill:
    source-dirs: app
    main: Main.hs
    dependencies:
      - freewill
      - optparse-generic
