name:                freewillit
version:             0.1.0.0
homepage:            https://github.com/githubuser/alksjdhflaksjhdf#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - servant-server
  - wai
  - warp
  - wai-util
  - bytestring
  - http-types
  - mtl

library:
  source-dirs: src
  exposed-modules: Lib

executables:
  freewillit:
    source-dirs: app
    main: Main.hs
    dependencies: freewillit
