resolver: lts-8.18
packages:
  - '.'
  - location:
      git: https://github.com/sordina/servant-auth.git
      commit: 52f8436
    subdirs: ["servant-auth-swagger", "servant-auth-server"]
    extra-dep: true
  # - location: /Users/lyndon/Code/servant-auth
  # - subdirs: ["servant-auth-server"]
  # - extra-dep: true
flags: {}
extra-package-dbs: []
extra-deps:
  - wai-util-0.8
  - http-accept-0.2
  - servant-options-0.1.0.0
  - servant-auth-0.2.7.0
  - generic-lens-0.2.0.0
