resolver: lts-8.8
packages: [ '.' ]
flags: {}
extra-package-dbs: []
extra-deps:
  - wai-util-0.8
  - http-accept-0.2
  - servant-auth-0.2.6.1
  - servant-auth-server-0.2.6.1
  - servant-options-0.1.0.0
  - servant-auth-swagger-0.2.6.1
